ALTER TABLE posts ADD COLUMN IF NOT EXISTS location_name TEXT DEFAULT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS location_lat DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS location_lng DOUBLE PRECISION DEFAULT NULL;
